# version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: mysite/.env
        required: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    env_file:
      - path: mysite/.env
        required: true
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
  
volumes:
  mysql_data: