version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: mysite/.env
        required: true
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - path: mysite/.env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: