# version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: mysite/.env
        required: true
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file:
      - path: mysite/.env
        required: true
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: