version: '3.4'

services:
  server:
    image: findeas
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - path: mysite/.env
        required: true
volumes:
  db_data: