# Generated by Django 5.0.6 on 2024-06-21 19:22

import django.db.models.deletion
import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sma', models.FloatField(blank=True)),
                ('sd', models.FloatField(blank=True)),
                ('ub', models.FloatField(blank=True)),
                ('lb', models.FloatField(blank=True)),
                ('macd', models.FloatField()),
                ('macd_signal', models.FloatField()),
                ('gain', models.FloatField()),
                ('loss', models.FloatField()),
                ('avg_gain', models.FloatField(blank=True)),
                ('avg_loss', models.FloatField(blank=True)),
                ('rs', models.FloatField(blank=True)),
                ('rsi', models.FloatField(blank=True)),
                ('rsi_6', models.FloatField(blank=True)),
                ('rsi_12', models.FloatField(blank=True)),
                ('weakMACD', models.IntegerField(validators=[website.validators.validate_weakMACD])),
                ('macd_diff', models.FloatField()),
                ('isLoss', models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding])),
                ('isCausion', models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding])),
                ('isGain', models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding])),
                ('isSafe', models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding])),
                ('flag', models.CharField(choices=[('Yellow', 'In warning'), ('Green', 'Safe'), ('Red', 'In danger')], max_length=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.stock')),
            ],
        ),
    ]
