# Generated by Django 5.0.6 on 2024-07-10 13:52

import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='avg_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='avg_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='flag',
            field=models.CharField(choices=[('Yellow', 'In warning'), ('Green', 'Safe'), ('Red', 'In danger')], default='Green', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isCausion',
            field=models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding]),
        ),
        migrations.AddField(
            model_name='stock',
            name='isGain',
            field=models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding]),
        ),
        migrations.AddField(
            model_name='stock',
            name='isLoss',
            field=models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding]),
        ),
        migrations.AddField(
            model_name='stock',
            name='isSafe',
            field=models.IntegerField(default=0, null=True, validators=[website.validators.validate_one_hot_encoding]),
        ),
        migrations.AddField(
            model_name='stock',
            name='lb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='macd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='macd_diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='macd_signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rsi_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rsi_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ub',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='weakMACD',
            field=models.IntegerField(blank=True, null=True, validators=[website.validators.validate_weakMACD]),
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
